using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ENT_CE.Catastro
{
    public class Cls_Identificacion_Socio_Economica_ENT
    {
        private int IDENTIFICACION_SOCIO_ECONOMICA_ID;
        private int COMERCIANTE_ID;
        private int ETNIA_ID;
        private int GENERO_ID;
        private int ESTADO_CIVIL_ID;
        private int NACIONALIDAD_ID;
        private int NIVEL_EDUCACION_ID;
        private int DISCAPACIDAD_ID;
        private string IDENTIFICACION_SOCIO_ECONOMICA_JEFE_FAMILIA;
        private string IDENTIFICACION_SOCIO_ECONOMICA_DEPENDIENTES;
        private int IDENTIFICACION_SOCIO_ECONOMICA_NUMERO_DEPENDIENTES;
        private string IDENTIFICACION_SOCIO_ECONOMICA_PARENTESCO;
        private int IDENTIFICACION_SOCIO_ECONOMICA_ESTADO;

        public int IDENTIFICACION_SOCIO_ECONOMICA_ID1 { get => IDENTIFICACION_SOCIO_ECONOMICA_ID; set => IDENTIFICACION_SOCIO_ECONOMICA_ID = value; }
        public int COMERCIANTE_ID1 { get => COMERCIANTE_ID; set => COMERCIANTE_ID = value; }
        public int ETNIA_ID1 { get => ETNIA_ID; set => ETNIA_ID = value; }
        public int GENERO_ID1 { get => GENERO_ID; set => GENERO_ID = value; }
        public int ESTADO_CIVIL_ID1 { get => ESTADO_CIVIL_ID; set => ESTADO_CIVIL_ID = value; }
        public int NACIONALIDAD_ID1 { get => NACIONALIDAD_ID; set => NACIONALIDAD_ID = value; }
        public int NIVEL_EDUCACION_ID1 { get => NIVEL_EDUCACION_ID; set => NIVEL_EDUCACION_ID = value; }
        public int DISCAPACIDAD_ID1 { get => DISCAPACIDAD_ID; set => DISCAPACIDAD_ID = value; }
        public string IDENTIFICACION_SOCIO_ECONOMICA_JEFE_FAMILIA1 { get => IDENTIFICACION_SOCIO_ECONOMICA_JEFE_FAMILIA; set => IDENTIFICACION_SOCIO_ECONOMICA_JEFE_FAMILIA = value; }
        public string IDENTIFICACION_SOCIO_ECONOMICA_DEPENDIENTES1 { get => IDENTIFICACION_SOCIO_ECONOMICA_DEPENDIENTES; set => IDENTIFICACION_SOCIO_ECONOMICA_DEPENDIENTES = value; }
        public int IDENTIFICACION_SOCIO_ECONOMICA_NUMERO_DEPENDIENTES1 { get => IDENTIFICACION_SOCIO_ECONOMICA_NUMERO_DEPENDIENTES; set => IDENTIFICACION_SOCIO_ECONOMICA_NUMERO_DEPENDIENTES = value; }
        public string IDENTIFICACION_SOCIO_ECONOMICA_PARENTESCO1 { get => IDENTIFICACION_SOCIO_ECONOMICA_PARENTESCO; set => IDENTIFICACION_SOCIO_ECONOMICA_PARENTESCO = value; }
        public int IDENTIFICACION_SOCIO_ECONOMICA_ESTADO1 { get => IDENTIFICACION_SOCIO_ECONOMICA_ESTADO; set => IDENTIFICACION_SOCIO_ECONOMICA_ESTADO = value; }
    }
}
