using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ENT_CE.Catastro
{
    public class Cls_Intervencion_Tecnica_Establecimiento_ENT
    {
        private int INTERVENCION_TECNICA_ESTABLECIMIENTO_ID;
        private int TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ID;
        private string INTERVENCION_TECNICA_ESTABLECIMIENTO_NOMBRE;
        private string INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_INICIO;
        private string INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_FIN;
        private int TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ESTADO;

        public int INTERVENCION_TECNICA_ESTABLECIMIENTO_ID1 { get => INTERVENCION_TECNICA_ESTABLECIMIENTO_ID; set => INTERVENCION_TECNICA_ESTABLECIMIENTO_ID = value; }
        public int TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ID1 { get => TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ID; set => TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ID = value; }
        public string INTERVENCION_TECNICA_ESTABLECIMIENTO_NOMBRE1 { get => INTERVENCION_TECNICA_ESTABLECIMIENTO_NOMBRE; set => INTERVENCION_TECNICA_ESTABLECIMIENTO_NOMBRE = value; }
        public string INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_INICIO1 { get => INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_INICIO; set => INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_INICIO = value; }
        public string INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_FIN1 { get => INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_FIN; set => INTERVENCION_TECNICA_ESTABLECIMIENTO_FECHA_FIN = value; }
        public int TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ESTADO1 { get => TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ESTADO; set => TIPO_INTERVENCION_TECNICA_ESTABLECIMIENTO_ESTADO = value; }
    }
}
